name: Build sitemap & RSS & lists
on:
  workflow_dispatch:
  push:
    paths:
      - 'articles/*.html'
      - 'index.html'
      - 'tools/build_sitemap_and_rss.py'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - uses: actions/setup-python@v5
        with: {python-version: '3.x'}
      - run: python tools/build_sitemap_and_rss.py
      - name: Commit changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add -A
            git commit -m "chore: rebuild sitemap, rss and lists"
            git push
          fi
