name: Patch affiliate links
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.html'
      - 'tools/patch_affiliate_links.py'
permissions:
  contents: write
jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - uses: actions/setup-python@v5
        with: {python-version: '3.x'}
      - run: python tools/patch_affiliate_links.py
      - name: Commit changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add -A
            git commit -m "chore: add rel=\"nofollow sponsored noopener\" to bot links"
            git push
          fi
